### DISCUSSION TITLE
Anubis bypass  extension - heads up

### DISCUSSION THREAD

**Discussion by xkpx64** [TecharoHQ/anubis#663] [General]
Just a heads up https://gitlab.com/zipdox/anubis-bypass

**Comment by Xe** [comment]
I'm aware of this. Please send future such things to security@techaro.lol

**Comment by guest20** [comment]
If I'm reading this right this extension bypasses anubis by just changing the user agent on any host that ever set an anubis cookie?

**Comment by thess** [comment]
Yup - seen it on my site...
```yaml
# anubis-bypass seen in the wild

- name: anubis-bypass
  user_agent_regex: (?i)anubis
  action: DENY
```
