### DISCUSSION TITLE
Configuration to challenge all requests

### DISCUSSION THREAD

**Discussion by insanitywholesale** [TecharoHQ/anubis#76] [General]
I'm not sure if this is a misunderstanding or misconfiguration on my part so I didn't want to open a potentially incorrect issue.
My goal is to challenge all requests no matter the user agent, path or address they have. Of course if the client has solved the challenge once, it should be let through without solving it again but on initial request I'd like the challenge to be required for everyone.

I tried to add a policy using the "everything" value for each of them and even all of them together:
```json
{
  "bots": [
    {
      "name": "challengealladdr",
      "remote_addresses": ["0.0.0.0/0"],
      "action": "CHALLENGE"
    },
    {
      "name": "challengeallpath",
      "path_regex": "^.*$",
      "action": "CHALLENGE"
    },
    {
      "name": "challengealluseragent",
      "user_agent_regex": ".*",
      "action": "CHALLENGE"
    }
  ]
}
```

This still allows a request with `curl` to get through.

My setup is a modified version of the example `docker-compose.yml`, I just changed the port to 8090 and moved the botPolicy.json bind mount to the anubis container and changed the container names:
```yaml
services:
  anubis:
    container_name: anubis
    image: ghcr.io/techarohq/anubis:latest
    environment:
      BIND: ":8090"
      DIFFICULTY: "5"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://nginx"
    ports:
      - 8090:8090
    networks:
      - intra
    volumes:
      - "./botPolicy.json:/data/cfg/botPolicy.json"
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - intra

networks:
  intra:
```

Is there a way to achieve this, am I missing something or is this a bug?
