### ISSUE TITLE
X-Real-Ip is sometimes not inferred when connection is local

### ISSUE THREAD

**Issue by mattxtaz** [TecharoHQ/anubis#103]
Since the workaround for X-Real-Ip not being set was added I have tried disabling Caddy from setting that header. It works fine for some requests but not others. How come this has an x-forwarded-for IP but x-real-ip hasn't been inferred from it?

`{"time":"2025-03-24T14:56:44.23571099Z","level":"ERROR","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).MaybeReverseProxy","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":182},"msg":"check failed","user_agent":"Mozilla/5.0 (compatible; Miniflux/2.2.6; +https://miniflux.app)","accept_language":"","priority":"","x-forwarded-for":"172.16.0.10","x-real-ip":"","err":"[misconfiguration] X-Real-Ip header is not set"}`

But it works fine for other requests. Is it because the IP is the same one as Anubis has within its own container so it's not trusting it? I'm using rootless podman/pasta networking which means Caddy, Anubis, and Miniflux will all be using 172.16.0.10 as their IP addresses locally within their respective containers.

`{"time":"2025-03-24T15:21:22.05447018Z","level":"INFO","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).PassChallenge","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":396},"msg":"challenge took","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0","accept_language":"en-GB,en;q=0.9,en-US;q=0.8","priority":"u=0, i","x-forwarded-for":"81.139.34.102","x-real-ip":"81.139.34.102","check_result":{"name":"bot/generic-browser","rule":"CHALLENGE"},"elapsedTime":625}`

**Comment by Delationnn** [comment]
I'm having that same issue too!

**Comment by BlitDev** [comment]
USE_REMOTE_ADDRESS is not working, I'm getting the same error with example compose.yaml.

![Image](https://github.com/user-attachments/assets/c103f872-8377-45b8-84e9-110b6d1d2eee)

I think expecting a reverse proxy/load balancer in front of Anubis by default is not a good idea.

Anubis should work by default on its own as well. I guess I'm not the only one who uses simple nginx/caddy for a static site and then wants to put Anubis in front of it, without putting anything in front of Anubis.

**Comment by SlyEcho** [comment]
Sorry about that, it is not released yet. You can try the current development build with the `main` tag.

Here is what I just tested and it works, there are two ways to enable this flag and here I try the command line option to make sure it is actually doing something.

```yaml
services:
  anubis-nginx:
    image: ghcr.io/techarohq/anubis:main
    command:
      - --use-remote-address # use command line explicitly so it would give an error if this is not supported
    environment:
      BIND: ":8080"
      DIFFICULTY: "5"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://nginx"
      #USE_REMOTE_ADDRESS: "true"
    ports:
      - 8081:8080
  nginx:
    image: nginx
```
---

> I think expecting a reverse proxy/load balancer in front of Anubis by default is not a good idea.

Anubis does not do SSL by itself, so that's why I think it is a good idea to have something in front of it. But maybe there is some other usecase I haven't thought of?
