### ISSUE TITLE
Problem when configuring in front of a static site

### ISSUE THREAD

**Issue by BlitDev** [TecharoHQ/anubis#223]
Hi, I've been trying to put Anubis in front of my static site, but there's a problem.

When I go to https://my.tld/, everything works as it should. But when I go to https://my.tld/anything, I get redirected to https://my.tld:8080/anything for some reason.

I have never worked with proxy in nginx, help me pls :)

My **compose.yaml**:
```yaml
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./my-site/:/my-site/
      - /etc/letsencrypt/live/my.tld/fullchain.pem:/tls-certs/fullchain.pem
      - /etc/letsencrypt/live/my.tld/privkey.pem:/tls-certs/privkey.pem
    ports:
      - 443:443
  anubis-nginx:
    image: ghcr.io/techarohq/anubis:main
    environment:
      BIND: ":8081"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://my.tld:8080"
```

My **nginx config**:
```
server {
    listen 80;
    server_name my.tld;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name my.tld;
    ssl_certificate /tls-certs/fullchain.pem;
    ssl_certificate_key /tls-certs/privkey.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        proxy_pass http://anubis-nginx:8081;
    }
}

server {
    listen 8080;
    server_name my.tld;

    root /my-site;
    index index.html;
}
```
