### ISSUE TITLE
Is there an option to set a relative root url?

### ISSUE THREAD

**Issue by jcormier** [TecharoHQ/anubis#231]
We have gitweb hosted at domain.com/gitweb.   If I setup apache like below

apache:
```
# Gitweb Pass connection to docker
ProxyRequests Off
ProxyPass /gitweb http://anubis-nginx:8080/gitweb
ProxyPassReverse /gitweb http://anubis-nginx:8080/gitweb
```

anubis still tries to load all its resources from domain.com/.within.website instead of domain.com/gitweb/.within.website

Is there an option to set a relative root url?

**Comment by SlyEcho** [comment]
There is currently no such option. The static assets like JavaScript files have the paths set in the source code and they can't easily change at runtime, at the same time it also can't use relative addressing because the challenge page could be served on any URL on the site.

**Comment by jcormier** [comment]
> at the same time it also can't use relative addressing because the challenge page could be served on any URL on the site.

Could you expand on this?  I am trying to get the challenge page to serve for /gitweb, am I approaching this incorrectly?

**Comment by SlyEcho** [comment]
Right now there is no option to do so. If it is possible, you could add another proxy directive to also forward `domain.com/.within.website` to Anubis.

**Comment by jcormier** [comment]
Note if I also add a proxy for the static files.  
```
ProxyPass /.within.website http://127.0.0.1:3334/.within.website
ProxyPassReverse /.within.website http://127.0.0.1:3334/.within.website
```

Things look better but I get the following error:  If I follow the link, the page says my ip isn't listed in DroneBL. I can also access other websites protected by Anubis...

`DroneBL reported an entry: DroneBLResponse(109), see https://dronebl.org/lookup?ip=xx.xx.xx.xx.`

**Comment by Xe** [comment]
Note for me: maybe this is another point in the favour of implementing #184.

**Comment by jcormier** [comment]
Switched to ghcr.io/techarohq/anubis:main which pulls in the updated bots file with dnsbl disabled

**Comment by JasonLovesDoggo** [comment]
If this isn't done in the next few days, feel free to ping me and I'll open a PR for it.

**Comment by JasonLovesDoggo** [comment]
> > If this isn't done in the next few days, feel free to ping me and I'll open a PR for it.
> 
> Bump

🫡 I'll try to get something in by tonight

**Comment by JasonLovesDoggo** [comment]
@jcormier Would you be able to verify that #294 serves your needs?

**Comment by jcormier** [comment]
Thanks I was able to use the docker image the pipeline created to test this build, nice setup.  Anubis now fetches its static files from /gitweb/.within.website so I don't need to the extra proxy line

```
    anubis-nginx:
        # image: ghcr.io/techarohq/anubis:latest
        image: ttl.sh/techaro/pr-294/anubis:24h # pull request 294
        environment:
            BIND: ":3334"
            DIFFICULTY: "4"
            METRICS_BIND: ":9090"
            SERVE_ROBOTS_TXT: "true"
            TARGET: "http://apache-gitweb"
            BASE_PREFIX: "/gitweb"
            # POLICY_FNAME: "/data/cfg/botPolicy.json"
        ports:
            - 127.0.0.1:3334:3334
```
