### ISSUE TITLE
Infinite redirect loop

### ISSUE THREAD

**Issue by vlnst** [TecharoHQ/anubis#263]
When playing and settings up Anubis I stumbled upon an infinite loop: I couldn't access my service behind Anubis, it kept saying "Done!" and continued calculating hash again and again.

The only thing to fix was to clear site's data. I'm not sure if users of my service will understand what to do and won't just stop using it altogether.

Not sure how to report this bug now, since I cleared site data in my main web browser...

**Comment by AresUII** [comment]
Suffered while attempting to use rl.bloat.cat today.

**Comment by JasonLovesDoggo** [comment]
> When playing and settings up Anubis I stumbled upon an infinite loop: I couldn't access my service behind Anubis, it kept saying "Done!" and continued calculating hash again and again.
> 
> The only thing to fix was to clear site's data. I'm not sure if users of my service will understand what to do and won't just stop using it altogether.
> 
> Not sure how to report this bug now, since I cleared site data in my main web browser...

Have you visited the site before? I'm guessing that it's due to an expired cookie somehow

**Comment by vlnst** [comment]
> Suffered while attempting to use rl.bloat.cat today.

Yep, sorry about that 🐈 

> Have you visited the site before? I'm guessing that it's due to an expired cookie somehow

Yes. It seems so

**Comment by c33s** [comment]
just tried to access https://anubis.techaro.lol/ no entrance without cookie :(

**Comment by Xe** [comment]
Configure your browser to store cookies.

**Comment by c33s** [comment]
if you are privacy aware and block js and cookies it is sad that the web nearly  gone. blocking other browsers like lynx or even wget for offline reading is sad for me. 
i understand where the need comes from but seeing everything behind google captcha, cloudflare challenges or other protection methods makes me feel sad. also normally it is no problem for people to come around such protections if they really want to. my assumption is that ai companies are such people which come around the protection and people who just want to surf the net in private are locked out.
i often get stuck at such enterence pages even after enabling cookies and js (mainly cloudlfare).

just thoughts i share, not a request to change something in anubis.

**Comment by Xe** [comment]
Yeah, I'm aware this sucks, but the AI companies don't store cookies.

**Comment by TTsdzb** [comment]
I've got this issue on chromium based browsers, without cookie blocked or js disabled. The browsers could visit <https://anubis.techaro.lol> fine, but redirect loops on my site.

I'm setting up like this: Caddy -> Anubis (Docker) -> Caddy (Docker)

Here's my outer Caddyfile (you can visit the domain to test it out):

```
blog.closure.cc {
        reverse_proxy 127.0.0.1:8923
}
```

Here's the docker-compose.yml:

```
services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    environment:
      BIND: ":8923"
      DIFFICULTY: "4"
      ED25519_PRIVATE_KEY_HEX: "<censored>"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://caddy"
      POLICY_FNAME: "/data/cfg/botPolicies.json"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
      COOKIE_DOMAIN: "blog.closure.cc"
      COOKIE_PARTITIONED: "true"
      SERVE_ROBOTS_TXT: "true"
    ports:
      - 127.0.0.1:8923:8923
    networks:
      - blog
    restart: always
    volumes:
      - "./botPolicies.json:/data/cfg/botPolicies.json:ro"
  caddy:
    image: caddy:alpine
    container_name: caddy
    hostname: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - blog
    volumes:
      - "./caddy-conf:/etc/caddy"
      - "./blog:/srv:ro"
      - "caddy_data:/data"
      - "caddy_config:/config"

networks:
  blog:

volumes:
  caddy_data:
  caddy_config:
```

Here's the inner Caddyfile:

```
:80 {
        root * /srv
        file_server
        try_files {path} /
}
```

Any ideas please?
