### ISSUE TITLE
[Bug] Custom policies not registering

### ISSUE THREAD

**Issue by ggtylerr** [TecharoHQ/anubis#285]
I'm using a docker compose setup like so:

```yaml
anubis-nginx:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      BIND: ":54301"
      COOKIE_DOMAIN: "ggtyler.dev"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      TARGET: "http://inv-nginx:3000"
      POLICY_FNAME: "/data/cfg/botPolicy.json"
      SERVE_ROBOTS_TXT: "true"
    ports:
      - 54301:54301
      - 59090:9090
    volumes:
      - "./botPolicy.json:/data/cfg/botPolicy.json:ro"
````

And on my bot policy file, I have something written like:

```json
{
  "bots": [
    {
      "name": "rss",
      "path_regex": "^/feed/.*$",
      "action": "ALLOW"
    },
    {
      "name": "embed",
      "path_regex": "^/embed/.*$",
      "action": "ALLOW"
    },
    {
      "name": "test",
      "user_agent_regex": "Mozilla test test test",
      "action": "ALLOW"
    }
  ]
}
```

However, none of these definitions seem to go through:

```sh
$ curl https://nyc1.iv.ggtyler.dev/api/v1/stats
{"version":"2.0","software":{"name":"invidious","version":"2025.04.04-713d4dd","branch":"master"},"openRegistrations":true,"usage":{"users":{"total":4712,"activeHalfyear":222,"activeMonth":39}},"metadata":{"updatedAt":1744948806,"lastChannelRefreshedAt":1744866521},"playback":{}}%

$ curl -A "Mozilla test test test" https://nyc1.iv.ggtyler.dev/api/v1/stats
<!doctype html><html lang="en"><head><title>Making sure you&#39;re not a bot!</title><link rel="stylesheet" href="/.within.website/x/xess/xess.min.css?cachebuster=v1.16.0"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="robots" content="noindex,nofollow"><style>

# resulting HTML from anubis
```

I can verify that botPolicy.json is being mounted on Docker via `docker inspect`, so it's seemingly not a docker issue. If I had to guess, the default policies are possibly overriding the custom ones? I'm not even sure if the rules are being added or if the file is just being completely ignored...

**Comment by Xe** [comment]
Hey, is this still an issue? I think I missed it in the notifications.

**Comment by derritter88** [comment]
Hello @Xe 

yes, it seems that the bot policy is being somehow ignored.
On my side I tried to configure different difficult values per http-agent but the only value that is being used is the env value "DIFFICULTY"

**Comment by DiegoPino** [comment]
@derritter88 what version of Anubis (container) are you running?

On the latest I can't replicate: I just copied your docker compose config/policy file. Only differences is i am not double quoting the mount

```
 volumes:
      - ./botPolicy.json:/data/cfg/botPolicy.json:ro
```

To validate, I changed your "test" rule to DENY

Got this
`
{"time":"2025-05-08T15:33:42.590675343Z","level":"INFO","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).checkRules","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":164},"msg":"explicit deny","user_agent":"Mozilla test test test","accept_language":"en-US,en;q=0.9","priority":"","x-forwarded-for":"","x-real-ip":"172.20.0.1","check_result":{"name":"bot/test","rule":"DENY"}}
`


Means it is working

**Comment by derritter88** [comment]
@DiegoPino 
I am using 1.17.1
`ghcr.io/techarohq/anubis:v1.17.1@sha256:4836f8b86a185f7be92e8c76bf03de73ce9ec793b61a27473a72c41811d07cd5`

I am running the container within Kubernetes and mounted the policy as config map:

deployment
```yaml
...
        volumeMounts:
          - name: config-anubis-volume
            mountPath: /data/cfg/botPolicy.json
            subPath: botPolicy.json
....
      volumes:
        - name: config-anubis-volume
          configMap:
            name: anubis-config
```


And the configmap would be:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-config
  namespace: anubis
data:
  botPolicy.json: |
    {
      "bots": [
        {
          "import": "(data)/bots/ai-robots-txt.yaml"
        },
        {
          "import": "(data)/bots/cloudflare-workers.yaml"
        },
        {
          "import": "(data)/bots/headless-browsers.yaml"
        },
        {
          "import": "(data)/bots/us-ai-scraper.yaml"
        },
        {
          "import": "(data)/crawlers/googlebot.yaml"
        },
        {
          "import": "(data)/crawlers/bingbot.yaml"
        },
        {
          "import": "(data)/crawlers/duckduckbot.yaml"
        },
        {
          "import": "(data)/crawlers/qwantbot.yaml"
        },
        {
          "import": "(data)/crawlers/internet-archive.yaml"
        },
        {
          "import": "(data)/crawlers/kagibot.yaml"
        },
        {
          "import": "(data)/crawlers/marginalia.yaml"
        },
        {
          "import": "(data)/crawlers/mojeekbot.yaml"
        },
        {
          "import": "(data)/common/keep-internet-working.yaml"
        },
        {
          "name": "generic-bot-catchall",
          "user_agent_regex": "(?i:bot|crawler)",
          "action": "CHALLENGE",
          "challenge": {
            "difficulty": 16,
            "report_as": 4,
            "algorithm": "slow"
        }
      ],
      "dnsbl": false
    }
```

**Comment by Xe** [comment]
I don't think Kubernetes allows you to mount individual files. Try mounting the entire folder and read from that folder.

**Comment by DiegoPino** [comment]
Sorry @derritter88 I should have pinged @ggtylerr who reported this initially. I agree with @Xe, the mount path should be a folder as per examples https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap

**Comment by derritter88** [comment]
> I don't think Kubernetes allows you to mount individual files. Try mounting the entire folder and read from that folder.

It's a valid option as I am using this for other deployment as well and within the container I can `cat` the config file.

**Comment by Xe** [comment]
Can you try mounting it as a folder? I'll investigate on my local testing cluster.

**Comment by derritter88** [comment]
It's also not working.
My whole deployment yaml would be:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
  namespace: anubis
spec:
  selector:
    matchLabels:
      app: anubis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anubis
    spec:
      containers:
      - name: anubis
        image: ghcr.io/techarohq/anubis:v1.17.1@sha256:4836f8b86a185f7be92e8c76bf03de73ce9ec793b61a27473a72c41811d07cd5
        env:
          - name: "BIND"
            value: "0.0.0.0:8080"
          - name: "BIND_NETWORK"
            value: "tcp"
          - name: "DIFFICULTY"
            value: "4"
          - name: "POLICY_FNAME:"
            value: "/data/cfg/botPolicy.json"
          - name: "SERVE_ROBOTS_TXT"
            value: "1"
          - name: "TARGET"
            value: "http://127.0.0.1:80"
        volumeMounts:
          - name: config-anubis-volume
            mountPath: /data/cfg
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx:1.28.0-alpine@sha256:aed99734248e851764f1f2146835ecad42b5f994081fa6631cc5d79240891ec9
        volumeMounts:
          - name: config-nginx-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: config-anubis-volume
          configMap:
            name: anubis-config
        - name: config-nginx-volume
          configMap:
            name: nginx-config
```


and the config map would be:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-config
  namespace: anubis
data:
  botPolicy.json: |
    {
      "bots": [
        {
          "name": "test",
          "user_agent_regex": "Mozilla",
          "action": "DENY",
          "challenge": {
            "difficulty": 16,
            "report_as": 4,
            "algorithm": "slow"
        },
        {
          "name": "generic-bot-catchall",
          "user_agent_regex": "(?i:bot|crawler)",
          "action": "CHALLENGE",
          "challenge": {
            "difficulty": 16,
            "report_as": 4,
            "algorithm": "slow"
        }
      ],
      "dnsbl": false
    }
```


According to the container logs it sees the request and does only a challenge of "4" insteady of denying the request:

```log
Rule error IDs:
* ai-robots-txt: 8e399aa8f9f5d95a8cd0ad01284ea904784a854e9c6ab17ac9994f479d18aaed
* cloudflare-workers: 559e7f01707b78efda8b0ed791e13d0e0079fbf0e3c81c8dfaf2299537f8b666
* lightpanda: 8c4f381bde0fabcd361c88ec7f015d981fd7f80f3edcb16e670ed0bc772eb62d
* headless-chrome: b2dd0d54fa37a160ed04d152bcdde5df296a5861e0a6ef6a4fe845ef51d93be0
* headless-chromium: 900a0b88e9bcd4ae0772b55c198f6fb9e0e352da8af4ed61f7f72df1391f85a2
* us-artificial-intelligence-scraper: 5f0cb91e78d0499d22892c79e1520ccb378e98d3836effbd1ad675721bd46ac1
{"time":"2025-05-08T16:00:32.774176726Z","level":"WARN","source":{"function":"main.main","file":"github.com/TecharoHQ/anubis/cmd/anubis/main.go","line":259},"msg":"generating random key, Anubis will have strange behavior when multiple instances are behind the same load balancer target, for more information: see https://anubis.techaro.lol/docs/admin/installation#key-generation"}
{"time":"2025-05-08T16:00:32.774724115Z","level":"WARN","source":{"function":"main.main","file":"github.com/TecharoHQ/anubis/cmd/anubis/main.go","line":273},"msg":"REDIRECT_DOMAINS is not set, Anubis will only redirect to the same domain a request is coming from, see https://anubis.techaro.lol/docs/admin/configuration/redirect-domains"}
{"time":"2025-05-08T16:00:32.776624779Z","level":"INFO","source":{"function":"main.main","file":"github.com/TecharoHQ/anubis/cmd/anubis/main.go","line":315},"msg":"listening","url":"http://0.0.0.0:8080","difficulty":4,"serveRobotsTXT":true,"target":"http://127.0.0.1:80","version":"v1.17.1","use-remote-address":false,"debug-benchmark-js":false,"og-passthrough":true,"og-expiry-time":86400000000000,"base-prefix":"","cookie-expiration-time":604800000000000}
{"time":"2025-05-08T16:00:40.530878061Z","level":"INFO","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).PassChallenge","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":295},"msg":"challenge took","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0","accept_language":"de,en-US;q=0.7,en;q=0.3","priority":"u=0, i","x-forwarded-for":"","x-real-ip":"172.16.1.1","check_result":{"name":"bot/generic-browser","rule":"CHALLENGE"},"elapsedTime":510}
```
