### ISSUE TITLE
TARGET does not support unix, at odds with docs

### ISSUE THREAD

**Issue by mcint** [TecharoHQ/anubis#329]
The docs on environment variables claim that unix sockets [can be provided for the TARGET](https://anubis.techaro.lol/docs/admin/installation/#environment-variables).  There's no syntax example inline, but, as of the `latest` docker image, `v1.16.0`, anubis reports `unix` scheme is unsupported.

<details>
<summary>start up logs</summary>

* parsed from config, env: <code>anubis    | {"time":"2025-04-22T19:27:52.757186165Z","level":"INFO","source":{"function":"main.main","file":"github.com/TecharoHQ/anubis/cmd/anubis/main.go","line":289},"msg":"listening","url":"unix:/run/anubis/anubis-public.sock","difficulty":4,"serveRobotsTXT":true,"target":"unix:/run/anubis/upstream.sock","version":"v1.16.0","use-remote-address":false,"debug-benchmark-js":false,"og-passthrough":true,"og-expiry-time":172800000000000}</code>

* error, and trailing slash: <code>anubis    | {"time":"2025-04-22T19:27:57.344995537Z","level":"ERROR","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).RenderIndex","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":346},"msg":"failed to get OG tags","err":"http get failed: Get \"unix:/run/anubis/upstream.sock/\": unsupported protocol scheme \"unix\""}</code>
</details>

## Failed attempts
- `unix://` inline: `unix:///run/anubis/tgt.sock`
- `unix:`: `unix:/run/anubis/tgt.sock`
- `TARGET_NETWORK` (type), hypothesized pair to `TARGET` (address) by analogy to supported `BIND_NETWORK` (type) / `BIND` (address) pair
```
services:
  anubis: ...
    environment:
      BIND_NETWORK: "unix"
      BIND: "/run/anubis/anubis-public.sock"
      TARGET_NETWORK: "unix"                     # does not exist
      TARGET: "unix:///run/anubis/upstream.sock"
```
- bare path: `/run/anubis/tgt.sock`

Using latest, v1.16.0 
`#image: ghcr.io/techarohq/anubis:latest`
from 
`image: ghcr.io/techarohq/anubis@sha256:b8f59f4208b6639ea8c19e7c34eb26bcc7f1cc6b79e4f037cd99accf2c9de40b`.
