### ISSUE TITLE
Suspicion points

### ISSUE THREAD

**Issue by Xe** [TecharoHQ/anubis#338]
Right now Anubis is incredibly paranoid and aggressively challenges every client as much as possible. This works (especially for advertising and for raising awareness of the issue), but it may actually be too aggressive in practice. Instead of aggressively challenging every client as much as possible, I want to develop a "suspicion points" system where rules can add or remove suspicion to a client and if it's over a threshold, it'll get a challenge.

This would also need integration with #201 for having state based suspicion.

Imagine having something like:

```yaml
bots:
- name: generic-browser
  action: SUSPECT
  suspicion:
    delta: 1

suspicion:
  threshold: 1 # At one point, show a challenge
```

Maybe this would also integrate with #206 so that GeoIP based lookups can add suspicion, eg:

```yaml
bots:
# Add suspicion to clients in the US
- name: us-is-sus
  action: SUSPECT
  geoip:
    country_iso_code: US
  suspicion:
    delta: 1

# Remove suspicion from clients in the EU
- name: eu-is-all-good
  action: SUSPECT
  geoip:
    is_in_european_union: true
  suspicion:
    delta: -4
```

This would chain with #337 to have default rules that _remove_ suspicion for things that "look sensible". Maybe this would also integrate with ASN lookups or something to allow you to add suspicion to an entire ASN or reverse DNS lookups to allow you to apply suspicion there. I need to do more research.
