### ISSUE TITLE
Considering / Configuring Anubis response code

### ISSUE THREAD

**Issue by fnetX** [TecharoHQ/anubis#355]
Hi there,

we are currently testing a deployment of Anubis for Codeberg.org. However, we expect that the response code of error 200 results in a lot of unexpected breakage and support overhead, because debugging is harder.

For example, tools might correctly report connection issues if they receive an invalid response code. Serving data with "200 OK" could result in arbitrary issues like parsing issues, app crashes and much more. Even the Forgejo-native "webhook" test feature only checks for the 200 response code and would mark delivery as successful, although it might have been trapped by anubis.

I understand the motivation to trick crawlers into thinking they were successful, but this is probably not suitable for deployments that have legitimate and unknown automated traffic.

**Comment by Xe** [comment]
After sleeping on it, I think HTTP 401 is fine for the challenge page. I'll make this a goal for release +1!

**Comment by fnetX** [comment]
Please note that 401 is probably not the correct code here. See https://www.rfc-editor.org/rfc/rfc9110#status.401

> The server generating a 401 response MUST send a [WWW-Authenticate](https://www.rfc-editor.org/rfc/rfc9110#field.www-authenticate) header field ([Section 11.6.1](https://www.rfc-editor.org/rfc/rfc9110#field.www-authenticate))

Unless you can also generate a proper WWW-Authenticate header, I think the easiest would be to leave this configurable as a number and recommend to either specify 403 or something in the 5xx range.

**Comment by Xe** [comment]
Roger, I think I'm gonna put this config in the bot policy file under a block like:

```yaml
response_codes:
  CHALLENGE: 403 # Forbidden, what Cloudflare sends on its challenge page
  DENY: 403 # Forbidden
```

The defaults will look something like this:

```yaml
response_codes:
  CHALLENGE: 200 # OK, lie to the client to make bots think they won
  DENY: 200 # OK
```
