### ISSUE TITLE
Environment docs for Caddy

### ISSUE THREAD

**Issue by Xe** [TecharoHQ/anubis#392]
TL;DR:

```
# Caddyfile

:443 {
	tls your@email.address

	reverse_proxy http://anubis:3000 {
		header_up X-Real-Ip {remote_host}
		header_up X-Http-Version {http.request.proto}
	}
}
```

Test with this:

```yaml
# docker-compose.yaml

services:
  caddy:
    image: caddy:2.10.0
    pull_policy: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  anubis:
    image: ghcr.io/techarohq/anubis:main
    pull_policy: always
    environment:
      BIND: ":3000"
      TARGET: http://httpdebug:3000

  httpdebug:
    image: ghcr.io/xe/x/httpdebug
    pull_policy: always
```
