### ISSUE TITLE
Anubis ignoring bot policy yaml on Kubernetes

### ISSUE THREAD

**Issue by derritter88** [TecharoHQ/anubis#479]
Dear all,

I have deployed Anubis on my K3s Kubernetes cluster which in general works as I am being challenged but it's ignoring the botPolicy.yaml file.

Configuration as follows:

*K8s deployment*
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
  namespace: anubis
spec:
  selector:
    matchLabels:
      app: anubis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anubis
    spec:
      containers:
      - name: anubis
        image: ghcr.io/techarohq/anubis:v1.17.1@sha256:4836f8b86a185f7be92e8c76bf03de73ce9ec793b61a27473a72c41811d07cd5
        env:
          - name: "BIND"
            value: "0.0.0.0:8080"
          - name: "BIND_NETWORK"
            value: "tcp"
          - name: "COOKIE_DOMAIN"
            value: "hks-projekt.at"
          - name: "DIFFICULTY"
            value: "4"
          - name: "ED25519_PRIVATE_KEY_HEX"
            value: "xxx"
          - name: "POLICY_FNAME:"
            value: /data/cfg/botPolicy.yaml
          - name: "SERVE_ROBOTS_TXT"
            value: "1"
          - name: "TARGET"
            value: "http://127.0.0.1:80"
        volumeMounts:
          - name: config-anubis-volume
            mountPath: /data/cfg/botPolicy.yaml
            subPath: botPolicy.yaml
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx:1.28.0-alpine@sha256:aed99734248e851764f1f2146835ecad42b5f994081fa6631cc5d79240891ec9
        volumeMounts:
          - name: config-nginx-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: config-anubis-volume
          configMap:
            name: anubis-config
        - name: config-nginx-volume
          configMap:
            name: nginx-config
```

*botPolicy.yaml*
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-config
  namespace: anubis
data:
  botPolicy.yaml: |
    ## Anubis has the ability to let you import snippets of configuration into the main
    ## configuration file. This allows you to break up your config into smaller parts
    ## that get logically assembled into one big file.
    ##
    ## Of note, a bot rule can either have inline bot configuration or import a
    ## bot config snippet. You cannot do both in a single bot rule.
    ##
    ## Import paths can either be prefixed with (data) to import from the common/shared
    ## rules in the data folder in the Anubis source tree or will point to absolute/relative
    ## paths in your filesystem. If you don't have access to the Anubis source tree, check
    ## /usr/share/docs/anubis/data or in the tarball you extracted Anubis from.

    bots:
    # Pathological bots to deny
    # This correlates to data/bots/ai-robots-txt.yaml in the source tree
    - import: (data)/bots/ai-robots-txt.yaml
    - import: (data)/bots/cloudflare-workers.yaml 
    - import: (data)/bots/headless-browsers.yaml
    - import: (data)/bots/us-ai-scraper.yaml

    # Allow common "keeping the internet working" routes (well-known, favicon, robots.txt)
    - import: (data)/common/keep-internet-working.yaml

    # # Punish any bot with "bot" in the user-agent string
    # # This is known to have a high false-positive rate, use at your own risk
    - name: generic-bot-catchall
      user_agent_regex: (?i:bot|crawler)
      action: CHALLENGE
      challenge:
        difficulty: 16  # impossible
        report_as: 4    # lie to the operator
        algorithm: slow # intentionally waste CPU cycles and time

    # Generic catchall rule
    - name: generic-browser
      user_agent_regex: >-
        Mozilla|Opera
      action: DENY

    - name: jellyfin
      user_agent_regex: 'Ktor client'
      action: ALLOW

    dnsbl: false

    # By default, send HTTP 200 back to clients that either get issued a challenge
    # or a denial. This seems weird, but this is load-bearing due to the fact that
    # the most aggressive scraper bots seem to really really want an HTTP 200 and
    # will stop sending requests once they get it.
    status_codes:
      CHALLENGE: 200
      DENY: 200 
```

*Logs*
```
Rule error IDs:
* ai-robots-txt: 8e399aa8f9f5d95a8cd0ad01284ea904784a854e9c6ab17ac9994f479d18aaed
* cloudflare-workers: 559e7f01707b78efda8b0ed791e13d0e0079fbf0e3c81c8dfaf2299537f8b666
* lightpanda: 8c4f381bde0fabcd361c88ec7f015d981fd7f80f3edcb16e670ed0bc772eb62d
* headless-chrome: b2dd0d54fa37a160ed04d152bcdde5df296a5861e0a6ef6a4fe845ef51d93be0
* headless-chromium: 900a0b88e9bcd4ae0772b55c198f6fb9e0e352da8af4ed61f7f72df1391f85a2
* us-artificial-intelligence-scraper: 5f0cb91e78d0499d22892c79e1520ccb378e98d3836effbd1ad675721bd46ac1
{"time":"2025-05-09T06:34:39.265207479Z","level":"WARN","source":{"function":"main.main","file":"github.com/TecharoHQ/anubis/cmd/anubis/main.go","line":273},"msg":"REDIRECT_DOMAINS is not set, Anubis will only redirect to the same domain a request is coming from, see https://anubis.techaro.lol/docs/admin/configuration/redirect-domains"}
{"time":"2025-05-09T06:34:39.26586507Z","level":"INFO","source":{"function":"main.main","file":"github.com/TecharoHQ/anubis/cmd/anubis/main.go","line":315},"msg":"listening","url":"http://0.0.0.0:8080","difficulty":4,"serveRobotsTXT":true,"target":"http://127.0.0.1:80","version":"v1.17.1","use-remote-address":false,"debug-benchmark-js":false,"og-passthrough":true,"og-expiry-time":86400000000000,"base-prefix":"","cookie-expiration-time":604800000000000}
{"time":"2025-05-09T06:35:06.591692919Z","level":"INFO","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).PassChallenge","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":295},"msg":"challenge took","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0","accept_language":"de,en-US;q=0.7,en;q=0.3","priority":"u=0, i","x-forwarded-for":"","x-real-ip":"172.16.1.1","check_result":{"name":"bot/generic-browser","rule":"CHALLENGE"},"elapsedTime":2914}
```
