### ISSUE TITLE
Nginx Subrequest Authentication "Redirect domain not allowed."

### ISSUE THREAD

**Issue by thomasdelorge** [TecharoHQ/anubis#491]
Hello everyone, 

I’m using Nginx Proxy Manager as a reverse proxy for all my services, but I’ve encountered an issue when trying to configure Anubis in front of my WAN services. All of this is deployed via Docker. 

✅ When I deploy a single instance of Anubis for one service, it works perfectly (TARGET="$container_name:$port").
❌ However, I run into problems when attempting to deploy a single Anubis instance for multiple services.  

I followed the instructions in this guide: [Anubis Documentation on Subrequest Authentication ](https://anubis.techaro.lol/docs/admin/configuration/subrequest-auth): 
- TARGET = " "
- NPM config :
```
location /.within.website/ {
    proxy_pass http://anubis:80; # I deployed anubis on port 80, same docker network as nginx
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_pass_request_body off;
    proxy_set_header content-length "";
    auth_request off;
}

location @redirectToAnubis {
    return 307 /.within.website/?redir=$scheme://$host$request_uri;
    auth_request off;
}

location / {
    auth_request /.within.website/x/cmd/anubis/api/check;
    error_page 401 = @redirectToAnubis;
}
```

- My docker compose for Anubis:
```
services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    restart: always
    environment:
      TZ: Europe/Paris
      BIND: ":80"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: " "
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
      REDIRECT_DOMAINS: "test.thomasdelorge.fr,test2.thomasdelorge.fr"
      COOKIE_DOMAIN: "thomasdelorge.fr"
    #ports:
      #- 8080:8080
    volumes:
      - "/docker/anubis/config/botpolicy.yaml:/data/cfg/botPolicy.yaml:ro"
    networks:
      - docker_internal_nginx
      
networks:
  docker_internal_nginx:
    external: true
```

When I try to access [https://test.thomasdelorge.fr ](https://test.thomasdelorge.fr/), I am correctly redirected to the Anubis POW Challenge, but I receive a "Redirect domain not allowed." error on "[https://test.thomasdelorge.fr/.within.website/?redir=https://test.thomasdelorge.fr/ ](https://test.thomasdelorge.fr/.within.website/?redir=https://test.thomasdelorge.fr/)".

![Image](https://github.com/user-attachments/assets/d24f35ee-a821-4139-a157-760bc428dc53)

Container logs :
```
2025-05-11T12:50:23.85404534+02:00 ERROR source={"function":"github.com/TecharoHQ/anubis/lib.(*Server).RenderIndex","file":"github.com/TecharoHQ/anubis/lib/http.go","line":59} msg=failed to get OG tags user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0 accept_language=en-US,en;q=0.5 priority=u=0, i x-forwarded-for= x-real-ip=192.168.1.254 err=http get failed: Get "/.within.website/?redir=https://test.thomasdelorge.fr/": unsupported protocol scheme ""
```
I don’t understand why it fails with a null protocol scheme 😥.

I also tried modifying my REDIRECT_DOMAINS to "[https://test.thomasdelorge.fr,test.thomasdelorge.fr,thomasdelorge.fr,test2.thomasdelorge.fr ](https://test.thomasdelorge.fr,test.thomasdelorge.fr,thomasdelorge.fr,test2.thomasdelorge.fr/)," but the behavior remains the same.

Thank you for your help,
Thomas
