### ISSUE TITLE
Anubis + HTMX can be kinda blursed

### ISSUE THREAD

**Issue by Xe** [TecharoHQ/anubis#498]
If tangled.sh gets a form of this working, ship as docs:

```yaml
- name: allow-htmx-iff-already-passed-challenge
  action: ALLOW
  expression:
    all:
      - '"Cookie" in headers'
      - 'headers["Cookie"].contains("anubis-auth")' # cookie name is about to change
      - '"Hx-Request" in headers'
      - 'headers["Hx-Request"] == "true"'
```
