### ISSUE TITLE
Google-Read-Aloud fails challenge

### ISSUE THREAD

**Issue by dchandekstark** [TecharoHQ/anubis#526]
This is just to report a presumably legit request (from a Google IP) that apparently can't pass the challenge.  Easy enough to allow by rule.  Not sure whether anything else should be done about it.

{"time":"2025-05-20T15:46:05.805963665Z","level":"DEBUG","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).PassChallenge","file":"/src/anubis/lib/anubis.go","line":324},"msg":"hash does not match","user_agent":"Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36 (compatible; Google-Read-Aloud; +https://support.google.com/webmasters/answer/1061943)","accept_language":"en-US","priority":"","x-forwarded-for":"66.249.83.96","x-real-ip":"66.249.83.96","check_result":{"name":"bot/generic-browser","rule":"CHALLENGE"},"got":"0000a432d97d1a6e2860e25d02f40915cebe80464cf901e493ed98c3827d984d","want":"1a20d8cc59103cc8aceb2d714bce40423292d1d69c803e50c5612338e2e5b28b"}

**Comment by Xe** [comment]
This is the service NotebookLM uses to read things to generate its horrible podcasts. Probably going to have to make that an opt in rule for administrators.

**Comment by dchandekstark** [comment]
For anyone who's interested, here's a custom policy that I'm using:

```yaml
# https://developers.google.com/search/docs/crawling-indexing/read-aloud-user-agent
# Fails challenge - https://github.com/TecharoHQ/anubis/issues/526
- name: google-read-aloud
  action: ALLOW
  user_agent_regex: Google-Read-Aloud
```
