### ISSUE TITLE
No CIDR support in expressions, no "match-all" in regular rules

### ISSUE THREAD

**Issue by thess** [TecharoHQ/anubis#569]
Thanks for this add-on service - Our site(s) are returning to somewhat normal responsiveness. This problem can be solved with Nginx rules and maps but it would be nice to use Anubis for a solution.

Neither of the following rules work as hoped.
```
- name: deny-mirrors
  action: DENY
  user_agent_regex: (?i)wget|lftp
  remote_addresses: [ "123.42.60.0/24", "5.62.42.5/32" ]
```
-- or --
```
- name: deny-mirrors
  action: DENY
  expression:
    all:
      - userAgent.matches("(?i)wget|lftp")
      - remoteAddress in [ "123.42.60.0/24", "5.62.42.5/32" ]
```
The first rule doesn't work when the UA is "Wget" for example. The pattern matcher quits on first found item and the IP is not considered (re-ordering doesn't help). The second is not possible since the 'list' of addresses is just strings and no CIDR IP matching is possible (AFAICT).
