### ISSUE TITLE
Connection refused on backend

### ISSUE THREAD

**Issue by huskeee** [TecharoHQ/anubis#604]
I am running nginx/alpine:mainline and anubis:latest on Docker. Nginx is running in host network mode, and Anubis's `TARGET` is set to `127.0.0.1:3923`. In my nginx config, I have added the Anubis `proxy_pass` directives to the HTTPS server block and have moved everything else to a server block listening on port 3923 on localhost. 
Whenever I try and access my site, I get 502 Bad Request on my browser, while Anubis logs show:
```
{"time":"2025-06-02T20:48:38.461291536Z","level":"INFO","msg":"http: proxy error: dial tcp 127.0.0.1:3923: connect: connection refused"}
``` 

Nginx is actually listening on port 3923 (verified with curl).

**Comment by huskeee** [comment]
Setting `network_mode` to `host` on Anubis' docker compose definition seems to fix it, but I'm not sure that's what it should be doing.

**Comment by Xe** [comment]
Generally you want something like this:

```mermaid
flowchart LR
    LB(Load Balancer)
    An(Anubis)
    App(App)

    LB --> An
    An --> App
```

```yaml
services:
  nginx:
    image: nginx:mainline
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./load-balancer/conf.d:/etc/nginx/conf.d" # reverse proxies to http://anubis:8080
      - "./load-balancer/www:/usr/share/nginx/html"
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      BIND: ":8080"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://app"
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    volumes:
      - "./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
  app:
    image: nginx:mainline
    volumes:
      - "./app/nginx:/etc/nginx/conf.d"
      - "./app/www:/usr/share/nginx/html"
```

I'd personally not suggest running an nginx container in `--net=host` mode, but if you must, then you need to make sure that the `--net=host` nginx container points to the IP address of the Anubis container. I don't remember how to determine this statically. The IP address of the Anubis container can change every time Anubis is restarted, which can be a pain in practice.
