### ISSUE TITLE
Traefik doesn't provision TLS certificates for services behind Anubis

### ISSUE THREAD

**Issue by antonlyap** [TecharoHQ/anubis#633]
I tried running this configuration: https://anubis.techaro.lol/docs/admin/environments/traefik/.

It is a great idea in general, but Traefik won't provision a TLS certificate for `example.com`. The browser shows a self-signed certificate warning. This is because `example.com` is on an entrypoint with no cert resolver.

As a solution, I suggest adding a third dummy entrypoint with TLS enabled. This will force Traefik to acquire a certificate for the service:

```yaml
services:
  traefik:
    # ... your configuration ...
    labels:
      - '--entrypoints.anubis-dummy.address=:3924'
      - '--entrypoints.anubis-dummy.asDefault=true'
      - '--entrypoints.anubis-dummy.http.tls.certResolver=le'
```

All routers will be assigned to two entrypoints at the same time (`anubis` and `anubis-dummy`), but only the `anubis` one (`:3923`) will be actually used.

I would be happy to submit a PR with the documentation update.
