### ISSUE TITLE
[SUPPORT] Need help connecting prometheus metrics with grafana

### ISSUE THREAD

**Issue by pompydev** [TecharoHQ/anubis#667]
Hi. I am trying to hook up anubis' prometheus metrics with grafana dashboard but trying to add `http://<private-ip>:9093` as data source fails with the following message:

```
Post "http://<private-ip>:9093/api/v1/query": dial tcp <private-ip>:9093: connect: connection refused - There was an error returned querying the Prometheus API.
```

There are no relevant logs from anubis when this happens, and other instances of [`prom/prometheus`](https://hub.docker.com/r/prom/prometheus) docker containers are running just fine so it's not that grafana isn't set up correctly.

Here is my docker compose:

```yml
services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    expose:
      - 8923
      - 9093:9093
    environment:
      - DIFFICULTY=4
      - SERVE_ROBOTS_TXT=true
      - METRICS_BIND=:9093
      - TARGET=http://<some-service>:3000
      - POLICY_FNAME=/data/cfg/botPolicy.yaml
      - OG_PASSTHROUGH=true
    volumes:
      - .../anubis.yaml:/data/cfg/botPolicy.yaml:ro

  ...
```
