### ISSUE TITLE
Option to return default OpenGraph tags instead of looking them up with the remote target

### ISSUE THREAD

**Issue by Xe** [TecharoHQ/anubis#681]
A request from a customer. This should be done in the policy file, something like:

```yaml
opengraph:
  enable: true
  default: # map[string]string
```
