### ISSUE TITLE
Anubis blocks low-harm clients such as git and curl on v1.20.0-pre1 (default configuration)

### ISSUE THREAD

**Issue by RoblKyogre** [TecharoHQ/anubis#700]
On the latest prerelease, it seems as though Anubis is challenging clients like `git`, `curl`, and `pacman` on the default bot policy config, causing those tools to break on instances protected by Anubis. Reverting to `v1.19.1` fixes the issue. In particular, I ran into this on my Forgejo instance:

```
$ git clone https://git.craftingcomrades.net/CraftingComrades/caddy-dockerfile-custom.git
Cloning into 'caddy-dockerfile-custom'...
fatal: https://git.craftingcomrades.net/CraftingComrades/caddy-dockerfile-custom.git/info/refs not valid: could not determine hash algorithm; is this a git repository?
```

```
$ curl https://git.craftingcomrades.net/CraftingComrades/caddy-dockerfile-custom
<!doctype html><html lang="en"><head><title>Making sure you&#39;re not a bot!</title><link rel="stylesheet" href="/.within.website/x/xess/xess.min.css?cachebuster=v1.20.0-pre1"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="robots" content="noindex,nofollow"><style>
        body,
        html {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-left: auto;
            margin-right: auto;
        }

        .centered-div {
            text-align: center;
        }

        #status {
            font-variant-numeric: tabular-nums;
        }

        #progress {
            display: none;
            width: 90%;
            width: min(20rem, 90%);
            height: 2rem;
            border-radius: 1rem;
            overflow: hidden;
            margin: 1rem 0 2rem;
                        outline-offset: 2px;
                        outline: #b16286 solid 4px;
                }

        .bar-inner {
            background-color: #b16286;
            height: 100%;
            width: 0;
            transition: width 0.25s ease-in;
        }
    </style><script id="anubis_version" type="application/json">"v1.20.0-pre1"
</script><script id="anubis_challenge" type="application/json">{"rules":{"algorithm":"metarefresh","difficulty":1,"report_as":1},"challenge":"f24cc09651feeeb6"}
</script><script id="anubis_base_prefix" type="application/json">""
</script></head><body id="top"><main><center><h1 id="title" class=".centered-div">Making sure you&#39;re not a bot!</h1></center><div class="centered-div"><img id="image" style="width:100%;max-width:256px;" src="/.within.website/x/cmd/anubis/static/img/pensive.webp?cacheBuster=v1.20.0-pre1"> <img style="display:none;" style="width:100%;max-width:256px;" src="/.within.website/x/cmd/anubis/static/img/happy.webp?cacheBuster=v1.20.0-pre1"><p id="status">Loading...</p><p>Please wait a moment while we ensure the security of your connection.</p><meta http-equiv="refresh" content="1; url=/.within.website/x/cmd/anubis/api/pass-challenge?challenge=f24cc09651feeeb6&amp;redir=%2FCraftingComrades%2Fcaddy-dockerfile-custom"></div><footer><center><p>Protected by <a href="https://github.com/TecharoHQ/anubis">[Anubis](https://github.com/TecharoHQ/anubis)</a> from <a href="https://techaro.lol">[Techaro](https://techaro.lol/)</a>. Made with ❤️ in 🇨🇦.</p><p>Mascot design by <a href="https://bsky.app/profile/celphase.bsky.social">[CELPHASE](https://bsky.app/profile/celphase.bsky.social)</a>.</p></center></footer></main></body></html>
```

Here's the relevant parts of the docker compose file I use to deploy Forgejo + Anubis:
```
services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis-forgejo
    restart: always
    environment:
      BIND: ":8080"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://server:3000"
    ports:
      - 3100:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- "3100:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: forgejo-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
```

**Comment by Xe** [comment]
It was an off-by-one error. For a quick fix, use this policy file:

```yaml
bots:
  - import: (data)/bots/ai-robots-txt.yaml
  - import: (data)/bots/cloudflare-workers.yaml
  - import: (data)/bots/headless-browsers.yaml
  - import: (data)/bots/us-ai-scraper.yaml

  - import: (data)/crawlers/googlebot.yaml
  - import: (data)/crawlers/bingbot.yaml
  - import: (data)/crawlers/duckduckbot.yaml
  - import: (data)/crawlers/qwantbot.yaml
  - import: (data)/crawlers/internet-archive.yaml
  - import: (data)/crawlers/kagibot.yaml
  - import: (data)/crawlers/marginalia.yaml
  - import: (data)/crawlers/mojeekbot.yaml

  - import: (data)/clients/git.yaml

  - import: (data)/common/keep-internet-working.yaml

  - name: generic-browser
    user_agent_regex: >-
      Mozilla|Opera
    action: CHALLENGE

dnsbl: false

thresholds:
  - name: minimal-suspicion
    expression: weight <= 0
    action: ALLOW

  - name: mild-suspicion
    expression:
      all:
        - weight > 0
        - weight < 10
    action: CHALLENGE
    challenge:
      algorithm: metarefresh
      difficulty: 1
      report_as: 1

  - name: moderate-suspicion
    expression:
      all:
        - weight >= 10
        - weight < 20
    action: CHALLENGE
    challenge:
      algorithm: fast
      difficulty: 2
      report_as: 2

  - name: extreme-suspicion
    expression: weight >= 20
    action: CHALLENGE
    challenge:
      algorithm: fast
      difficulty: 4
      report_as: 4
```

I'll roll -pre2 with this fix after work.
