### ISSUE TITLE
Support weight expressions in the BotEnvironment

### ISSUE THREAD

**Issue by JasonLovesDoggo** [TecharoHQ/anubis#704]
would make

```yml

    expression:
      all:
        - path.endsWith(".php")
        - weight > 5
```

possible
