### ISSUE TITLE
Feature Request: traefik middleware

### ISSUE THREAD

**Issue by imlonghao** [TecharoHQ/anubis#92]
Something like #16, but for traefik.

Example project https://github.com/libops/captcha-protect

**Comment by snoweuph** [comment]
this would be awesome.
Im hosting all my services behind traefik.

having it as middelware would make enabling anubis for specific services super easy

**Comment by zilti** [comment]
I mean... I don't really see the need for this? I just route all :443 traffic for the subdomains I want guarded to anubis, additionally listen on :3923 and do the actual per-subdomain routing there.

**Comment by Xe** [comment]
Can you write up some more about how you do that? That's a very interesting strategy.

**Comment by thefinn93** [comment]
Another option might be to add support for using Traefik's [ForwardAuth middleware](https://doc.traefik.io/traefik/middlewares/http/forwardauth/), which uses the same format as [nginx's auth_request module](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html).

**Comment by blade10101** [comment]
> I mean... I don't really see the need for this? I just route all :443 traffic for the subdomains I want guarded to anubis, additionally listen on :3923 and do the actual per-subdomain routing there.

I've set this up, but I get just 404 errors...  it dont seem to work that way

**Comment by imlonghao** [comment]
> > I mean... I don't really see the need for this? I just route all :443 traffic for the subdomains I want guarded to anubis, additionally listen on :3923 and do the actual per-subdomain routing there.
> 
> I've set this up, but I get just 404 errors... it dont seem to work that way

it works, show your configuration?

**Comment by snoweuph** [comment]
> 3923

Show your full config of treafik and anubis.

Alternatively check out the traefik dashboard to See what it is actually reading.
Maybe you got a typo in your labels (asuming youre using Labels)

**Comment by Pofilo** [comment]
I wrote a French article if it can help you.
https://www.pofilo.fr/post/2025/04/14-mise-en-place-anubis/

I had troubles because of the TLS configuration which I need to move from gitea to Anubis.

**Comment by snoweuph** [comment]
> I wrote a French article if it can help you.
> https://www.pofilo.fr/post/2025/04/14-mise-en-place-anubis/
> 
> I had troubles because of the TLS configuration which I need to move from gitea to Anubis.

Ofcourse treafik needs to terminate TLS bis before anubis.

After treafiks termination, everything should only be raw http

**Comment by blade10101** [comment]
> > > I mean... I don't really see the need for this? I just route all :443 traffic for the subdomains I want guarded to anubis, additionally listen on :3923 and do the actual per-subdomain routing there.
> > 
> > 
> > I've set this up, but I get just 404 errors... it dont seem to work that way
> 
> it works, show your configuration?

                                                   docker-compose.yml

services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    environment:
      BIND: ":8080"
      TARGET: "http://traefik:3923"
      DIFFICULTY: "4"  # Fast successful response with most devices, 5 is way more slow
      SERVE_ROBOTS_TXT: "true"
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm_default
      - traefik.http.services.anubis.loadbalancer.server.port=8080
      - traefik.http.routers.anubis.priority=1 # lowest priority
      - traefik.http.routers.anubis.rule=PathRegexp(`.*`) # route everything here
      - traefik.http.routers.anubis.entrypoints=https
      - traefik.http.routers.anubis.service=anubis
      - traefik.http.routers.anubis.tls.certresolver=myresolver
    networks:
      - npm_default
    restart: unless-stopped

  traefik:
    image: traefik:3.3
    container_name: "traefik"
    ports:
      - "80:80" # Enterpoint http
      - "443:443" # Entrypoint https
      - "100.117.196.19:8088:8080" # Dashboard
      - "8008:8008"
    volumes:
      - /srv/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /srv/traefik/acme.json:/etc/traefik/acme.json
      - /srv/traefik/config:/etc/traefik/config
      - /srv/traefik/logs:/var/log/traefik
    networks:
      - npm_default
    labels:
      #traefik.http.routers.api.rule: Host(`traefik.darkness.services`)
      #traefik.http.routers.api.entryPoints: https
      #traefik.http.routers.api.service: api@internal
      traefik.enable: true
      #traefik.http.routers.api.middlewares: auth@file
      # Redirect any HTTP to HTTPS
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.routers.http.rule: PathPrefix(`/`)
      traefik.http.routers.http.middlewares: redirect-to-https
      traefik.http.routers.http.tls: false
    environment:
      DOCKER_HOST: dockersocket
      CF_DNS_API_TOKEN: **Redacted**
    restart: unless-stopped
    depends_on:
      - dockersocket
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dockersocket:
    container_name: traefik-dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - npm_default
    environment:
      CONTAINERS: 2
      POST: 0
    privileged: true
    restart: always
  whoam:
    image: traefik/whoami:latest
    networks:
      - npm_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=npm_default"
      - "traefik.http.routers.whoam.entrypoints=anubis"
      - "traefik.http.services.whoam.loadbalancer.server.port=80"
      - "traefik.http.routers.whoam.service=whoam"
      - "traefik.http.routers.whoam.rule=Host(`whoam.darkness.services`)"
      - "traefik.http.routers.whoam.tls.certresolver=myresolver"
networks:
  npm_default:
    external: true


                                        traefik.yml

api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  http:
    address: 80
  https:
    address: :443
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: darkness.services 
            sans:
              - '*.darkness.services' 
      middlewares:
        - securityHeaders@file 
        - rate-limit@file 

  anubis:
    address: :3923
serversTransport:
  insecureSkipVerify: true

providers:
  providersThrottleDuration: 2s
  file:
    directory: /etc/traefik/config
    watch: true
  docker:
    watch: true
    network: npm_default 
    endpoint: "tcp://dockersocket:2375"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.darkness.services`)"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: **Redacted** 
      storage: /etc/traefik/acme.json
      dnsChallenge: 
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"

**Comment by witten** [comment]
I'm also getting 404s when trying to use Anubis with Traefik, using pretty much the documented configuration. I've also tried moving the TLS config to the Anubis container's labels, as suggested above. No luck.

IMO the fact that people are having difficulty getting this configuration working is a great argument for having Traefik middleware for Anubis.

**Comment by witten** [comment]
Okay, I finally got it working. This is with Traefik v3. I think the problem was actually the `traefik.http.routers.target.service=target` I had included from [the documentation](https://anubis.techaro.lol/docs/admin/environments/traefik). That was yielding errors like:

```
2025-05-22T17:27:49Z ERR error="the service \"target@docker\" does not exist" entryPointName=anubis routerName=target@docker
```

Once I removed that label, the 404s went away and everything seemed to work. Note that I'm also doing the TLS config labels on the Anubis container rather than the target container.

I recommend potentially removing that line from the documentation, so that others don't get hung up on this problem. @blade10101: Looking at your config, this may be your issue as well.

**Comment by witten** [comment]
> the line is needed though?

🤷 

Just reporting what I saw on my machine.

**Comment by andrewzah** [comment]
@snoweuph @witten `traefik.http.services.<name>.loadbalancer.server.port=<port>` is not necessarily needed. Traefik uses [port detection](https://doc.traefik.io/traefik/providers/docker/#port-detection) by default.

So *if* the image defines e.g. `EXPOSE 8080`, then you can omit those lines. But Traefik will certainly error if you don't get the service name right.

Anyways I get a 404 when I set `traefik.http.routers.<name>.entrypoints=anubis` regardless- it first redirects first to Anubis, and then after a redirect it's a 404.

**Comment by dpi0** [comment]
@andrewzah after an hour of tinkering, this finally worked for me. was also getting 404 after seeing anubis.

i failed to notice the subtle removal of `certresolver: cloudflare` from the protected service. from the [full example config](https://anubis.techaro.lol/docs/admin/environments/traefik/#full-example-config)

//traefik.yml (only the entryPoints section)
```yaml
...
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http3:
      advertisedPort: 443
  anubis:
    address: :3923
...
```

//anubis/compose.yml
```yaml
services:
  anubis:
    container_name: anubis
    image: ghcr.io/techarohq/anubis:v1.20.0
    environment:
      BIND: :8080
      TARGET: http://traefik:3923
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    labels:
      traefik.enable: true
      traefik.http.routers.anubis.entrypoints: websecure
      traefik.http.routers.anubis.priority: 1
      traefik.http.routers.anubis.rule: PathRegexp(`.*`)
      traefik.http.services.anubis.loadbalancer.server.port: 8080
      traefik.http.routers.anubis.tls.certresolver: cloudflare
    networks:
      - frontend
networks:
  frontend:
    external: true
```

//rimgo/compose.yml (an example service to protect)
```yaml
services:
  rimgo:
    container_name: rimgo
    image: codeberg.org/rimgo/rimgo:1.3.0
    restart: unless-stopped
    user: 65534:65534 # equivalent to `nobody`
    read_only: true
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    environment:
      PRIVACY_COUNTRY: $PRIVACY_COUNTRY
      PRIVACY_PROVIDER: $PRIVACY_PROVIDER
      PRIVACY_CLOUDFLARE: true
      PRIVACY_NOT_COLLECTED: true
      PRIVACY_IP: true
      PRIVACY_URL: true
      PRIVACY_DEVICE: true
      PRIVACY_DIAGNOSTICS: false
      FIBER_PREFORK: false
      ADDRESS: 0.0.0.0
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.rimgo.entrypoints: anubis
      traefik.http.routers.rimgo.rule: "Host(`${FQDN}`)"
      traefik.http.services.rimgo.loadbalancer.server.port: 3000
      traefik.http.routers.rimgo.middlewares: hdrs@file,ratelimit@file
      # CAUTION: DO NOT INCLUDE- traefik.http.routers.rimgo.tls.certresolver: cloudflare HERE, otherwise a 404 is seen fsr
    networks:
      - frontend
networks:
  frontend:
    external: true
```

**Comment by dpi0** [comment]
the only problem i haven't been able to solve is to get my custom middlewares working when anubis is set as the entrypoint.

like the security headers set don't apply on the hosted site.

when tested with <https://securityheaders.com>

like this test conducted on a site protected with anubis: <https://securityheaders.com/?q=git.euph.dev&followRedirects=on>

```yaml
services:
  rimgo:
    container_name: rimgo
    image: codeberg.org/rimgo/rimgo:1.3.0
    restart: unless-stopped
    user: 65534:65534 # equivalent to `nobody`
    read_only: true
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    environment:
      PRIVACY_COUNTRY: $PRIVACY_COUNTRY
      PRIVACY_PROVIDER: $PRIVACY_PROVIDER
      PRIVACY_CLOUDFLARE: true
      PRIVACY_NOT_COLLECTED: true
      PRIVACY_IP: true
      PRIVACY_URL: true
      PRIVACY_DEVICE: true
      PRIVACY_DIAGNOSTICS: false
      FIBER_PREFORK: false
      ADDRESS: 0.0.0.0
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.rimgo.entrypoints: anubis
      traefik.http.routers.rimgo.rule: "Host(`${FQDN}`)"
      traefik.http.services.rimgo.loadbalancer.server.port: 3000
      # CAUTION: DO NOT INCLUDE- traefik.http.routers.rimgo.tls.certresolver: cloudflare HERE, otherwise a 404 is seen fsr
      traefik.http.routers.rimgo.middlewares: rimgo-hdr
      traefik.http.middlewares.rimgo-hdr.headers.browserXssFilter: true
      traefik.http.middlewares.rimgo-hdr.headers.contentTypeNosniff: true
      traefik.http.middlewares.rimgo-hdr.headers.frameDeny: true
      traefik.http.middlewares.rimgo-hdr.headers.forceSTSHeader: true
      traefik.http.middlewares.rimgo-hdr.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.rimgo-hdr.headers.stsPreload: true
      traefik.http.middlewares.rimgo-hdr.headers.stsSeconds: 63072000
      traefik.http.middlewares.rimgo-hdr.headers.referrerPolicy: "strict-origin-when-cross-origin"
      traefik.http.middlewares.rimgo-hdr.headers.permissionsPolicy: "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(self), sync-xhr=()"

    networks:
      - frontend
networks:
  frontend:
    external: true
```

when `traefik.http.routers.rimgo.entrypoints` is set to `websecure` and `traefik.http.routers.rimgo.tls.certresolver` is set to `cloudflare` only then my security headers apply.
